# Generated by Django 3.1 on 2020-09-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(choices=[('HR', 'Croatia'), ('ME', 'Montenegro'), ('BA', 'Bosnia and Herzegovina'), ('RS', 'Serbia'), ('HU', 'Hungary'), ('SI', 'Slovenia'), ('IT', 'Italy')], default='HRV', max_length=3),
        ),
    ]
